[機能#0829] footerの追加
mpppk/tatoe pull request #181
Opened 2021-09-04 07:01 UTC by okashige

### 実装内容

footerのレイアウト、項目、導線の追加
- ３つの項目「Top, 新規作成, マイページ」のアイコン、ページ遷移制御
- Topとその他ページにフッターが追加されるようにfooterを追加

![image](https://user-images.githubusercontent.com/14093191/132085829-3346f1cd-e6b2-4509-9292-1086598bd080.png)

2021-09-04 17:12 UTC, mpppk commented
よさそう！細かい修正だけコメントしました

2021-09-04 17:12 UTC, mpppk requested changes

2021-09-04 17:12 UTC, mpppk commented on app/components/Footer.tsx
> +        <Link href={Routes.UserPage({ userId: session.userId as string })}>
session.userIdに応じて切り替えてるのはLinkのhrefだけだと思うので、コンポーネント自体は共有するのでどうでしょう?

2021-09-04 17:12 UTC, mpppk commented on app/core/layouts/Layout.tsx
> +  contentWrapp: {
pが一つ多い?contentWrap?

2021-09-04 17:12 UTC, mpppk commented on app/pages/index.tsx
> +      <Footer />
そうか、トップページはLayout使ってないのか
ここもいずれLayout使うようにしたいっすね

2021-09-04 17:13 UTC, mpppk commented on app/pages/index.tsx
> +      <Footer />
このPRでは対応不要です

2021-09-05 02:40 UTC, okashige commented on app/core/layouts/Layout.tsx
> +  contentWrapp: {
修正しました

2021-09-05 02:41 UTC, okashige commented on app/components/Footer.tsx
> +        <Link href={Routes.UserPage({ userId: session.userId as string })}>
変えてみました

2021-09-05 02:42 UTC, okashige commented
修正しました

2021-09-05 10:23 UTC, mpppk approved these changes

2021-09-05 10:23 UTC, mpppk commented
対応あざした！

2021-09-05 10:23 UTC, merged